#server.port=8089

server:
  port: 8089
spring:
  datasource:
    url: jdbc:h2:./db/JobSearch;AUTO_SERVER=true
    username: root
    password: 2565
    driver-class-name: org.h2.Driver

#  sql:
#    init:
#      mode: always

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  h2:
    console:
      enabled: false

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

  file:
    name: logs/spring.log